# Site settings
title: Septic Sense
description: "Your guide to septic system maintenance, care, and solutions. Expert advice for homeowners."

# For a Netlify deployment, it's best to leave the url and baseurl blank.
# Netlify automatically handles the URL, and your site is at the root, not a sub-directory.
url: ""
baseurl: ""

# Author/Owner
author:
  name: Septic Sense

# Build settings
theme: minima
plugins:
  - jekyll-feed
