# Backend configuration
backend:
  name: git-gateway
  repo: septicsense/Septic-Sense
  branch: main

# Media files will be stored in this directory in your repository
media_folder: "assets/images"
# The public-facing path to the media folder
public_folder: "/assets/images"

# Content collections
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/posts
    label: "Posts" # Used in the UI
    folder: "_posts" # THE MOST IMPORTANT PART: This is where your Jekyll posts are located.
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template for new posts: YYYY-MM-DD-title.md
    fields: # The fields for each document, which correspond to the front matter in your markdown files.
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Published", name: "published", widget: "boolean", default: true }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Categories", name: "categories", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
